### ISSUE TITLE
Consider `drush qd` to install, serve, and login to Drupal

### ISSUE THREAD

**Issue by bighappyface** [Jeff-Cardwell/adug_from_scratch_build#5]
Idea: the README example of a site install demonstrated a MySQL-based approach but D8 does really well with SQLite, and PHP server is super helpful.

Using this repo I was able to run the following to run and test the site provided by this guide:

`vendor/bin/drush qd --use-existing --uri=http://localhost:8383 --profile=standard`

**Comment by jeff-cardwell** [comment]
I agree that presenting more options for data source might be a good idea, but since most tutorials assume MySQL I think it might muddy the water to show alternatives in this one. As for PHP server, I kinda feel the same way.  I think it might be out of scope for the tutorial.  I'm glad it works for that too, though. :)  I certainly hadn't tested it.
